In [3]:
import collections
import numpy as np

import helper
import numpy as np
import project_tests as tests
import pydot

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import plot_model

from keras.models import Model
from keras.layers import GRU, Input, Dense, TimeDistributed, Activation, RepeatVector, Bidirectional
from keras.layers.embeddings import Embedding
from keras.optimizers import Adam
from keras.losses import sparse_categorical_crossentropy
from keras.models import Sequential

C:\Users\France\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## Multilayer perceptron
Define a Multilayer perceptron mobel for binary classification. The model has 10 inputs, 3 hidden layers with 10, 20, 10 neurons and output layers is 1 output.
Rectified linear activation funcions are used in the hidden layes and a sigmoid activation function is used in the output layer for binary classification.

In [4]:
visible = Input(shape=(10,)) #specifies shape of data, the layer takes a shape that is a tuple, when input data is one-dimensional you must add on dimension (2,)""""
hidden1= Dense(10, activation='relu')(visible) #first layer must specify the no. of imputs. you connect pairwise, a bracket notation is use such that after the layer is created, the layer gets the input specified in the brackets""""
hidden2= Dense(20, activation='relu')(hidden1) # activation relu is linear, no. neurons=n.inputs
hidden3=Dense(10, activation='relu')(hidden2)
output = Dense(1, activation= 'sigmoid')(hidden3) #activation sigmoid gives a single output
model = Model(inputs=visible, outputs=output)
#summarize layers
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 10)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_3 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
Total params: 551
Trainable params: 551
Non-trainable params: 0
_________________________________________________________________


In [8]:
# plot graph
plot_model(model, to_file='multilayer_perceptron_graph.png')

<img src="multilayer_perceptron_graph.png">

In [7]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)


array([[4, 1],
       [2, 2]])

In [21]:
a = np.array([[1, 2, 4, 3, 4]])
c= np.matrix([[1, 2, 4, 3, 4, 3, 7, 3, 4, 13], [1, 2, 4, 3, 4, 3, 7, 3, 4, 13], [1, 2, 4, 3, 4, 3, 7, 3, 4, 13], [1, 2, 4, 3, 4, 3, 7, 3, 4, 13], [1, 2, 4, 3, 4, 3, 7, 3, 4, 13]])
print(np.dot(a,c))


[[ 14  28  56  42  56  42  98  42  56 182]]


In [20]:
a.shape()

AttributeError: 'list' object has no attribute 'shape'

In [22]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
print(np.zeros((5)))

[0. 0. 0. 0. 0.]


In [24]:
print(np.zeros((5, 1)))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [25]:
print(np.zeros((1, 5)))

[[0. 0. 0. 0. 0.]]
